### ISSUE TITLE
Introduction Section

### ISSUE THREAD

**Issue by adonayb-ami** [hughsie/uefi-sbom-best-practices#14]
Can we add Silicon Vendor to the list below? The SI is the initial point of the FW supply chain in most cases contributing micro code, reference code, management code, etc.  
"... the Firmware Vendor that produces the bulk of the source code, the ODM (Original Design Manufacturer) that compiles it with other additional code and adds additional binaries, and the OEM (Original Equipment Manufacturer) ..."

**Comment by hughsie** [comment]
Isn't a silicon vendor just a component vendor? I'm not sure I see the distinction. The idea of silicon gets messy when we're talking about gables and ip blocks.
