### ISSUE TITLE
Required Attributes Section - Hash

### ISSUE THREAD

**Issue by adonayb-ami** [hughsie/uefi-sbom-best-practices#17]
"•	MUST  have a file hash that is generated from all the source files , ..."

The definition of "all the source files" can be ambiguous here. 
Specifically, should it include source files of the libraries? 
If yes, should it include full graph of interdependent libraries or just the libraries directly consumed by the image?
Without the libraries or with just the directly linked libraries, the hash is not very useful as it does not fully describe image composition (for example, image may use OpenSSL indirectly via a proxy CryptoLib). With the libraries, the complexity of hash creation is high; it will probably require additional tooling.
In the context of SBOM per code base, this requirement translates to a hash of all the files in the source tree, which is time-consuming but insignificant.

**Comment by hughsie** [comment]
All the implementations so far just use the .c and .h files. Maybe that needs to be more explicit.
