### ISSUE TITLE
SBoM Information Flow Section

### ISSUE THREAD

**Issue by adonayb-ami** [hughsie/uefi-sbom-best-practices#19]
"To comply with Executive Order 14028, OEM vendors SHOULD also publish either the SPDX or CycloneDX SBoM  export as a downloadable file on the public device webpage."

- It'd be helpful to have some explanation on CoSWID to SPDX/CycloneDX mapping and preferred tooling options for better consistency.

**Comment by hughsie** [comment]
Makes sense, something like `uswid --load foo.bin --save foo.json` as examples perhaps?

**Comment by dickwilkins** [comment]
I agree. I thought this was missing in my latest review of the full document.
