### ISSUE TITLE
Whitepaper?

### ISSUE THREAD

**Issue by dickwilkins** [hughsie/uefi-sbom-best-practices#24]
The intro to the glossary says, "This whitepaper assumes..."

The term "whitepaper" has specific meanings in the context of standards organizations. I suggest that we use "document" instead of whitepaper. When (if) we promote the document to a specification, we could then change it to the term "specification".

Sorry for being so OCD about form and not content, but in the last 15, or so, years of my working in standards groups, I have seen this sort of thing cause all sorts of problems.

**Comment by hughsie** [comment]
@dickwilkins fixed! There are a few more additions on https://github.com/hughsie/uefi-sbom-best-practices/pulls if you have a few mins spare today.
