### ISSUE TITLE
Defragmented Firmware SBoM section 

### ISSUE THREAD

**Issue by robert-ami** [hughsie/uefi-sbom-best-practices#7]
I believe it was agreed during the call that defining which libraries should be mentioned in the component SBOM should be up to the component owner. It’s important to explicitly clarify that as an anti-literalists measure.

Additionally, we should probably provide some guidelines as to which libraries should be included into component SBOM. For example, third-party libraries, libraries with a different license.

**Comment by hughsie** [comment]
Isn't this sufficient?

	Each SBoM component **SHOULD** describe either:
	- A single *component*, as defined in the `glossary`_, or
	- An individually identifiable part of a *component* that has security and/or licensing implications, for example an image loading library used by a PE binary, or
	- Something that has security and/or licensing implications and was used to produce a *component,* but is not present in the *component* itself, for example a compiler used to produce a PE binary, or

or do you want something explicit? Maybe like https://github.com/hughsie/uefi-sbom-best-practices/pull/10 perhaps.
